name: Publish 

on:
  workflow_dispatch:  
  push:
    branches:
    - master
    
env:
  AZURE_APP_NAME: test-api-deploy
  AZURE_APP_PACKAGE_PATH: "./publish"
  
jobs:
  publish:
   runs-on: ubuntu-latest
   
   steps:
    - uses: actions/checkout@v3
    
    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore
      run: dotnet restore ./TestApiDeploy.sln
    
    - name: Build
      run: dotnet build ./TestApiDeploy.sln --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish ./TestApiDeploy.sln --configuration Release --no-build --output '${{ env.AZURE_APP_PACKAGE_PATH }}'
      
    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
       app-name: ${{ env.AZURE_APP_NAME }}
       publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
       package: "${{ env.AZURE_APP_PACKAGE_PATH }}"
      
      
    
    
  
 
  
  
